### ISSUE TITLE
@import rule being (partially) removed => broken CSS

### ISSUE THREAD

**Issue by hellocosmin** [codsen/email-remove-unused-css#12]
Hey, thanks for your work on this.

Spotted an issue where it's partially removing an `@import` rule (well, most of it). 

I get it why, it's not "used" anywhere in the HTML. But this shouldn't be removed, it's needed for web fonts where `<link>` is not an option.

![image](https://user-images.githubusercontent.com/1656595/31829075-ec66e1a8-b5c4-11e7-9acb-5a3a5b6612cf.png)

**Comment by revelt** [comment]
Good one, I'll try sort this tonight, can't promise, but should get my Monday

**Comment by hellocosmin** [comment]
Yup, working fine now, thank you!

**Comment by revelt** [comment]
phew
👍

**Comment by hellocosmin** [comment]
Happy New Year!

Need to re-open this, as I'm seeing a bug again.

Take a look at the following screenshot from the web app:

![image](https://user-images.githubusercontent.com/1656595/34875121-a1f6cbb6-f7a4-11e7-8da3-a218782076af.png)

If the HTML doesn't use any of those classes that I highlighted,

- the `@import` rule is (correctly) removed
- the `@media` query where that import is actually used, is incorrectly removed: the list with the CSS properties is still there, resulting in invalid CSS

Of course, as soon as I use one of those classes in my HTML, everything works fine:

![image](https://user-images.githubusercontent.com/1656595/34875230-12e06ce2-f7a5-11e7-869f-5e9b7f8af878.png)

**Comment by revelt** [comment]
Thank you. Sorry for this, I'll look into this asap.

**Comment by revelt** [comment]
Hi Cosmin, I'm looking at this and, actually, while `@import` is being removed, it's a bug too. According to the correct spec `@import` would be kept because this library would not be able to detect that it is unused. The second part, `@media` should be removed in whole if all its classes are deemed to be duplicate (which looks like they are). I recreated this case in unit tests and it should not take long to tweak the algorithm. Again, thanks for flagging this up.

**Comment by hellocosmin** [comment]
Hi Roy,

I completely agree. There's no way to know if what's in the `@import` is used or not - it might very well be a Google Fonts import that is used in `font-family` inline instead of a class.

And big thanks for being so quick to respond and look into it. Cheers!

**Comment by revelt** [comment]
Hi Cosmin, the package is updated, try it now. I'll update the front-end on [emailcomb.com](https://www.emailcomb.com/) soon. You can see the version of the API used, it's above Email Comb's logo.
