### ISSUE TITLE
postcss parser

### ISSUE THREAD

**Issue by stevenvachon** [codsen/email-remove-unused-css#2]
[postcss](https://npmjs.com/postcss)

This might denecessitate `settings.noThrowing`.

**Comment by revelt** [comment]
There are no external stylesheets on email templates, so imho PostCSS plugin is not the best idea. [PostHTML](https://github.com/code-and-send/posthtml-email-remove-unused-css), [Gulp](https://github.com/code-and-send/gulp-email-remove-unused-css/) plugins and [raw Node](https://github.com/code-and-send/email-remove-unused-css) library should be enough on the automation side...

**Comment by stevenvachon** [comment]
This wasn't a request for a PostCSS plugin, though. It was to use the PostCSS parser because it is superior to the parser you're currently using.

**Comment by revelt** [comment]
I want it then. Let's reopen. Thank you Steven.

**Comment by revelt** [comment]
closing as the new version does not use parsing at all, it's treating code as string now

**Comment by stevenvachon** [comment]
So, you wrote a CSS parser with regular expressions? Sounds like over-complication.

**Comment by revelt** [comment]
I achieved the same features with three for loops over the input string. Btw, regexes are used only for empty style tag cleanup and valid css name character identification. Have a look!
